### ISSUE TITLE
NameError: name 'clip' is not defined

### ISSUE THREAD

**Issue by ucasiggcas** [ahmedrashed-ml/MultiRec#1]
hi,dear
the clip in the [line](https://github.com/rcdnn/MultiRec/blob/master/Code/MultiRec.py#L297) is not defined before use,
```
Traceback (most recent call last):
  File "MultiRec.py", line 518, in <module>
    MultiRec(df_train,ItemData=UseItemData,UserData=UseUserData ,Graph=UseGraphData,lr=LEARNRATE,ureg=UserReg,ireg=ItemReg)
  File "MultiRec.py", line 297, in MultiRec
    pred_batch = clip(pred_batch)
NameError: name 'clip' is not defined

```
could you pls modify the error?
thx

**Comment by ahmedrashed-ml** [comment]
Hi, thank you for pointing out this issue. 
It should be solved now in the latest version
